### PR TITLE
Fix inline DefineMap.extend as a property

### LINKED ISSUE #148: Inline DefineMaps do not get converted to ObservableObject
This code:

```js
const TodosList = DefineList.extend({
    "#": DefineMap.extend({
        id: "number",
        name: "string"
    })
 });
```

...becomes:

```js
import { ObservableArray, ObservableObject } from "can";

class TodoList extends ObservableArray {
  static get props() {
    return {};
  }

  static get items() {
    return DefineMap.extend({
      id: "number",
      name: "string"
    });
  }
```

...but if the `DefineMap` is not inline:

```js
import { DefineList, DefineMap } from "can";

const Todo = DefineMap.extend({
  id: "number",
  name: "string"
});

const TodoList = DefineList.extend({
  "#": Todo
});
```

...it is converted correctly to an `ObservableObject`:

```js
import { ObservableArray, ObservableObject, type } from "can";
import DeepObservable from "can-deep-observable";

class Todo extends ObservableObject {
  static get props() {
    return {
      id: type.maybeConvert(Number),
      name: type.maybeConvert(String)
    };
  }

  static get propertyDefaults() {
    return DeepObservable;
  }

  static get seal() {
    return true;
  }
}

class TodoList extends ObservableArray {
  static get props() {
    return {};
  }

  static get items() {
    return type.maybeConvert(Todo);
  }
}
```

### PR DESCRIPTION
**Pull request by cherifGsoul**
This fixes inline `DefineMap` to `ObservableObject` transformation:

**From:** 
```js
const TodosList = DefineList.extend({
  "#": DefineMap.extend({
      id: "number",
      name: "string"
  })
});
```

**To:**

```js
const TodosList = DefineList.extend({
  "#": class Model extends ObservableObject {
    static get props() {
      return {
          id: "number",
          name: "string"
      };
    }
  }
});
```

Other codemods with lower order handle the rest of the transformations.

closes #148

### CODE REVIEW

File: src/utils/defineTransform.js [hunk 1]
```diff
@@ -35,7 +35,10 @@ export default function defineTransform ({
       varDeclaration = path.parentPath.value.id.name;
       classPath = path.parentPath.parentPath.parentPath;
     // Handle default exports
-    } else if (path.parentPath && path.parentPath.value && path.parentPath.value.type === 'ExportDefaultDeclaration') {
+    } else if (path.parentPath && path.parentPath.value &&
+               path.parentPath.value.type === 'ExportDefaultDeclaration' ||
+               path.parentPath.value.type === 'Property'
```
Comment (phillipskevin) [inline src/utils/defineTransform.js]: Perhaps this should be a separate `else` block? Combining it with default exports makes the comments a little confusing.

Comment (bmomberger-bitovi) [reply src/utils/defineTransform.js]: Also without parentheses (`()`) around the or-clause (`||`) it will fail if path.parentPath.value is undefined (order of operations with logical AND / OR)

Comment (cherifGsoul) [reply src/utils/defineTransform.js]: @phillipskevin Like this it will be another `else` for the same logic, how about updating the comment?

File: src/utils/defineTransform.js [hunk 2]
```diff
@@ -59,6 +56,10 @@ export default function defineTransform ({
         objectName: path.parentPath.value.left.object.name,
         propertyName: path.parentPath.value.left.property.name
       };
+    } else if (path.parentPath.value.type === 'Property') {
```
Comment (bmomberger-bitovi) [inline src/utils/defineTransform.js]: This still seems like it might throw an exception if path.parentPath.value is undefined.  I would suggest making a local var before the if/else block:  `var parentPathValueType = path.parentPath && path.parentPath.value && path.parentPath.value.type;`  Then you can use it in each of the predicates.

File: src/utils/defineTransform.js [hunk 3]
```diff
@@ -1,6 +1,8 @@
 import { createClass, createMethod } from './classUtils';
 import replaceRefs from './replaceRefs';
 
+const transformInlineMap = (path) => path.value.arguments.length === 2 ?  path.value.arguments[0].value : 'Model';
```
Comment (phillipskevin) [inline src/utils/defineTransform.js]: Why call this Model? Can it just be a class expression without a name?

Comment (cherifGsoul) [reply src/utils/defineTransform.js]: Done!

File: src/templates/can-observable-object/observable-object-inline-output.js [hunk 4]
```diff
@@ -0,0 +1,10 @@
+const TodosList = DefineList.extend({
+  "#": class  extends ObservableObject {
```
Comment (phillipskevin) [inline src/templates/can-observable-object/observable-object-inline-output.js]: It seems like there are two spaces here. Can that be avoided?
